spring.datasource.url=jdbc:postgresql://localhost:5432/personal?stringtype=unspecified
spring.datasource.username=postgres
spring.datasource.password=nishan@90
spring.datasource.driver-class-name=org.postgresql.Driver
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.mail.username=your@email.com
spring.mail.password=your_password

jwt.secret=12345678901234567890123456789012