spring.application.name=client
server.port=8081
spring.jackson.default-property-inclusion=non_null
spring.jackson.time-zone=UTC

spring.config.import=optional:file:${APP_CONFIG_PATH:/home/nidhan/Desktop/Nishan/github/personal/config.properties}

spring.autoconfigure.exclude=org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration


springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.try-it-out-enabled=true
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.use-credentials=true
springdoc.swagger-ui.tags-sorter=alpha

logging.level.org.springframework.security=DEBUG